### ISSUE TITLE
Render pipeline切换

### ISSUE THREAD

**Issue by heyhuihui1** [lijuhong1981/Unity3MXLoader#2]
请问这个项目可以将HDRP切换成URP吗？如果可以的话，如何切换呢？

**Comment by lijuhong1981** [comment]
可以的，在Unity3MXTile.cs文件下，找到meshRender.material = new Material(Shader.Find("HDRP/Lit")); 
把“HDRP/Lit”替换成“Universal Render Pipeline/Lit”，或者你自己编写的Shader
